import JSZip from "jszip";

export type PptxElement = { kind: "text" | "shape" | "image"; x: number; y: number; w: number; h: number; rotate?: number; text?: string; fill?: string; stroke?: string; radius?: number; src?: string };
export type PptxSlide = { elements: PptxElement[]; width: number; height: number; text: string[] };
export type PptxDeck = { slides: PptxSlide[]; name: string; source: string };

const clean = (value: string) => value.replace(/\s+/g, " ").trim();
const local = (node: Element | Attr) => node.localName || ("name" in node ? node.name.split(":").pop() : "") || "";
const attr = (node: Element | null, names: string[], fallback = "") => { if (!node) return fallback; for (const attribute of Array.from(node.attributes)) if (names.some((name) => local(attribute).toLowerCase() === name.toLowerCase().split(":").pop())) return attribute.value; return fallback; };
const child = (node: Element, name: string) => Array.from(node.children).find((item) => local(item) === name) ?? null;
const descendants = (node: Element, name: string) => Array.from(node.getElementsByTagNameNS("*", name));
const resolvePath = (base: string, target: string) => { const parts = [...base.split("/").slice(0, -1), ...target.replace(/^\//, "").split("/")]; const result: string[] = []; parts.forEach((part) => { if (!part || part === ".") return; if (part === "..") result.pop(); else result.push(part); }); return result.join("/"); };
const dataUrl = (path: string, bytes: Uint8Array) => { let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); const ext = path.split(".").pop()?.toLowerCase(); const mime = ext === "png" ? "image/png" : ext === "jpg" || ext === "jpeg" ? "image/jpeg" : ext === "gif" ? "image/gif" : "image/svg+xml"; return `data:${mime};base64,${btoa(binary)}`; };
const textOf = (node: Element) => Array.from(node.getElementsByTagNameNS("*", "t")).map((item) => clean(item.textContent ?? "")).filter(Boolean).join(" ");
const colorOf = (node: Element | null, fallback: string) => { const color = node ? descendants(node, "srgbClr")[0] : undefined; const value = color ? attr(color, ["val"]) : ""; return value ? `#${value}` : fallback; };

export async function readPptx(file: File): Promise<PptxDeck> {
  const zip = await JSZip.loadAsync(await file.arrayBuffer()); const parse = (xml: string) => new DOMParser().parseFromString(xml, "application/xml");
  const presentation = parse(await zip.file("ppt/presentation.xml")?.async("text") ?? ""); const size = descendants(presentation.documentElement, "sldSz")[0]; const width = Number(attr(size, ["cx"], "12192000")); const height = Number(attr(size, ["cy"], "6858000"));
  const presentationRels = parse(await zip.file("ppt/_rels/presentation.xml.rels")?.async("text") ?? ""); const slideTargets = new Map<string, string>(); descendants(presentationRels.documentElement, "Relationship").forEach((rel) => { if (attr(rel, ["Type"]).includes("/slide")) slideTargets.set(attr(rel, ["Id"]), attr(rel, ["Target"])); });
  const fallback = Object.keys(zip.files).filter((path) => /^ppt\/slides\/slide\d+\.xml$/.test(path)).sort((a, b) => Number(a.match(/\d+/)?.[0]) - Number(b.match(/\d+/)?.[0])); const idNodes = descendants(presentation.documentElement, "sldId"); const candidatePaths = idNodes.map((id) => { const target = slideTargets.get(attr(id, ["id"])); return target ? `ppt/${target.replace(/^\.\//, "")}` : ""; }); const slidePaths = candidatePaths.length && candidatePaths.every((path) => Boolean(zip.file(path))) && new Set(candidatePaths).size === candidatePaths.length ? candidatePaths : fallback;
  const media = new Map<string, string>(); for (const path of Object.keys(zip.files).filter((name) => name.startsWith("ppt/media/"))) media.set(path, dataUrl(path, await zip.files[path].async("uint8array")));
  const slides = await Promise.all(slidePaths.map(async (path) => { const doc = parse(await zip.file(path)?.async("text") ?? ""); const slide: PptxSlide = { elements: [], width, height, text: [] }; const relPath = path.replace(/\/slides\/slide(\d+)\.xml$/, "/slides/_rels/slide$1.xml.rels"); const relDoc = parse(await zip.file(relPath)?.async("text") ?? ""); const imageRels = new Map<string, string>(); descendants(relDoc.documentElement, "Relationship").forEach((rel) => { if (attr(rel, ["Type"]).includes("/image")) imageRels.set(attr(rel, ["Id"]), resolvePath(path, attr(rel, ["Target"]))); });
    const tree = descendants(doc.documentElement, "spTree")[0]; const nodes = tree ? Array.from(tree.children).filter((node) => ["sp", "pic", "cxnSp"].includes(local(node))) : [];
    nodes.forEach((node) => { const props = descendants(node, "spPr")[0] ?? node; const xfrm = descendants(node, "xfrm")[0]; const off = xfrm ? descendants(xfrm, "off")[0] : null; const ext = xfrm ? descendants(xfrm, "ext")[0] : null; const x = Number(attr(off, ["x"], "0")) / width * 100; const y = Number(attr(off, ["y"], "0")) / height * 100; const w = Number(attr(ext, ["cx"], "0")) / width * 100; const h = Number(attr(ext, ["cy"], "0")) / height * 100; const text = textOf(node); const blip = descendants(node, "blip")[0]; const embed = attr(blip, ["embed"]); const imagePath = imageRels.get(embed); const kind = imagePath && media.has(imagePath) ? "image" : text ? "text" : "shape"; const element: PptxElement = { kind, x, y, w, h, rotate: Number(attr(xfrm, ["rot"], "0")) / 60000, text, fill: colorOf(descendants(props, "solidFill")[0], text ? "transparent" : "#ffffff22"), stroke: colorOf(descendants(props, "ln")[0], "#ffffff44"), radius: attr(descendants(props, "prstGeom")[0], ["prst"]) === "roundRect" ? 12 : 2, src: imagePath ? media.get(imagePath) : undefined }; if (text) slide.text.push(text); if (w > 0 && h > 0) slide.elements.push(element); });
    if (!slide.text.length) slide.text = Array.from(doc.getElementsByTagNameNS("*", "t")).map((item) => clean(item.textContent ?? "")).filter(Boolean); if (!slide.elements.length && slide.text.length) slide.text.forEach((text, index) => slide.elements.push({ kind: "text", x: 8, y: 8 + index * 8, w: 82, h: 6, text, fill: "transparent", stroke: "transparent" })); return slide;
  }));
  return { slides, name: file.name.replace(/\.pptx$/i, ""), source: file.name };
}
