import JSZip from "jszip";
import { XMLParser } from "fast-xml-parser";

export type PptxElement = { kind: "text" | "shape" | "image"; x: number; y: number; w: number; h: number; rotate?: number; text?: string; fill?: string; stroke?: string; radius?: number; src?: string; };
export type PptxSlide = { elements: PptxElement[]; width: number; height: number; text: string[] };
export type PptxDeck = { slides: PptxSlide[]; name: string; source: string };

const clean = (text: string) => text.replace(/\s+/g, " ").trim();
const attr = (node: any, key: string, fallback = "") => node?.[`@_${key}`] ?? node?.[`@_${key.toLowerCase()}`] ?? fallback;
const arr = (value: any) => value == null ? [] : Array.isArray(value) ? value : [value];
const color = (node: any, fallback: string) => { const srgb = node?.srgbClr; const scheme = node?.schemeClr; if (typeof srgb === "string") return `#${srgb}`; if (srgb?.["@_val"]) return `#${srgb["@_val"]}`; if (typeof scheme === "string") return `var(--${scheme})`; if (scheme?.["@_val"]) return `#${scheme["@_val"]}`; return fallback; };
const dataUrl = (path: string, bytes: Uint8Array) => { let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); const ext = path.split(".").pop()?.toLowerCase(); const mime = ext === "png" ? "image/png" : ext === "jpg" || ext === "jpeg" ? "image/jpeg" : ext === "gif" ? "image/gif" : "image/svg+xml"; return `data:${mime};base64,${btoa(binary)}`; };
const textNodes = (node: unknown): string[] => { if (!node || typeof node !== "object") return typeof node === "string" ? [clean(node)] : []; if (Array.isArray(node)) return node.flatMap(textNodes); return Object.entries(node as Record<string, unknown>).flatMap(([key, value]) => key === "t" ? (typeof value === "string" ? [clean(value)] : textNodes(value)) : key.startsWith("@_") ? [] : textNodes(value)); };

export async function readPptx(file: File): Promise<PptxDeck> {
  const zip = await JSZip.loadAsync(await file.arrayBuffer()); const parser = new XMLParser({ ignoreAttributes: false, removeNSPrefix: true });
  const pres = parser.parse(await zip.file("ppt/presentation.xml")?.async("text") ?? ""); const size = pres?.presentation?.sldSz; const width = Number(attr(size, "cx", "12192000")); const height = Number(attr(size, "cy", "6858000"));
  const relText = await zip.file("ppt/_rels/presentation.xml.rels")?.async("text") ?? ""; const rels = parser.parse(relText); const relItems = arr(rels?.Relationships?.Relationship); const slideTargets = new Map<string, string>(); relItems.forEach((rel: any) => { const type = String(attr(rel, "Type")); if (type.includes("/slide")) slideTargets.set(String(attr(rel, "Id")), String(attr(rel, "Target"))); });
  const slideIds = arr(pres?.presentation?.sldIdLst?.sldId); const paths = slideIds.map((item: any) => `ppt/${slideTargets.get(String(attr(item, "r:id"))) ?? "slides/slide1.xml"}`); const fallback = Object.keys(zip.files).filter((path) => /^ppt\/slides\/slide\d+\.xml$/.test(path)).sort(); const slidePaths = paths.length ? paths : fallback;
  const media = new Map<string, string>(); for (const path of Object.keys(zip.files).filter((name) => name.startsWith("ppt/media/"))) media.set(path, dataUrl(path, await zip.files[path].async("uint8array")));
  const slides = await Promise.all(slidePaths.map(async (path, index) => { const xml = parser.parse(await zip.file(path)?.async("text") ?? ""); const slide: PptxSlide = { elements: [], width, height, text: [] }; const root = xml?.sld?.cSld?.spTree; const slideRels = parser.parse(await zip.file(path.replace(/slides\/slide(\d+)\.xml$/, "slides/_rels/slide$1.xml.rels"))?.async("text") ?? ""); const imageRels = new Map<string, string>(); arr(slideRels?.Relationships?.Relationship).forEach((rel: any) => { const type = String(attr(rel, "Type")); if (type.includes("/image")) imageRels.set(String(attr(rel, "Id")), `ppt/${String(attr(rel, "Target")).replace(/^\.\.\//, "")}`); });
    const items = [...arr(root?.sp), ...arr(root?.pic), ...arr(root?.cxnSp)]; items.forEach((item: any) => { const xfrm = item?.spPr?.xfrm ?? item?.nvPicPr?.["p:cNvPr"]?.xfrm ?? item?.xfrm; const off = xfrm?.off ?? {}; const ext = xfrm?.ext ?? {}; const x = Number(attr(off, "x")) / width * 100; const y = Number(attr(off, "y")) / height * 100; const w = Number(attr(ext, "cx")) / width * 100; const h = Number(attr(ext, "cy")) / height * 100; const rotate = Number(attr(xfrm, "rot", "0")) / 60000; const texts = textNodes(item?.txBody).filter(Boolean); const blip = item?.blipFill?.blip; const embed = attr(blip, "r:embed"); const imagePath = imageRels.get(embed); const shapeFill = item?.spPr?.solidFill; const isImage = Boolean(imagePath && media.has(imagePath)); const element: PptxElement = { kind: isImage ? "image" : texts.length ? "text" : "shape", x, y, w, h, rotate, text: texts.join(" "), fill: color(shapeFill, texts.length ? "transparent" : "#ffffff22"), stroke: color(item?.spPr?.ln?.solidFill, "#ffffff44"), radius: item?.spPr?.prstGeom?.["@_prst"] === "roundRect" ? 12 : 2, src: imagePath ? media.get(imagePath) : undefined }; if (element.text) slide.text.push(element.text); if (element.w > 0 && element.h > 0) slide.elements.push(element); }); return slide; }));
  return { slides, name: file.name.replace(/\.pptx$/i, ""), source: file.name };
}
