import JSZip from "jszip";
import { XMLParser } from "fast-xml-parser";

export type PptxElement = { kind: "text" | "shape" | "image"; x: number; y: number; w: number; h: number; rotate?: number; text?: string; fill?: string; stroke?: string; radius?: number; src?: string };
export type PptxSlide = { elements: PptxElement[]; width: number; height: number; text: string[] };
export type PptxDeck = { slides: PptxSlide[]; name: string; source: string };

const clean = (text: string) => text.replace(/\s+/g, " ").trim();
const arr = (value: any) => value == null ? [] : Array.isArray(value) ? value : [value];
const readAttr = (node: any, names: string[], fallback = "") => { if (!node || typeof node !== "object") return fallback; const wanted = names.map((name) => name.toLowerCase().replace(/[^a-z0-9]/g, "")); const entry = Object.entries(node).find(([key]) => wanted.includes(key.replace(/^@_/, "").toLowerCase().replace(/[^a-z0-9]/g, ""))); return entry ? String(entry[1]) : fallback; };
const color = (node: any, fallback: string) => { const srgb = node?.srgbClr; if (typeof srgb === "string") return `#${srgb}`; if (srgb?.["@_val"]) return `#${srgb["@_val"]}`; return fallback; };
const textNodes = (node: unknown): string[] => { if (typeof node === "string") return [clean(node)]; if (!node || typeof node !== "object") return []; if (Array.isArray(node)) return node.flatMap(textNodes); return Object.entries(node as Record<string, unknown>).flatMap(([key, value]) => key === "t" ? textNodes(value) : key.startsWith("@_") ? [] : textNodes(value)); };
const zipPath = (baseFile: string, target: string) => { const parts = [...baseFile.split("/"), "..", ...target.split("/")]; const result: string[] = []; parts.forEach((part) => { if (!part || part === ".") return; if (part === "..") result.pop(); else result.push(part); }); return result.join("/"); };
const dataUrl = (path: string, bytes: Uint8Array) => { let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); const ext = path.split(".").pop()?.toLowerCase(); const mime = ext === "png" ? "image/png" : ext === "jpg" || ext === "jpeg" ? "image/jpeg" : ext === "gif" ? "image/gif" : "image/svg+xml"; return `data:${mime};base64,${btoa(binary)}`; };

export async function readPptx(file: File): Promise<PptxDeck> {
  const zip = await JSZip.loadAsync(await file.arrayBuffer()); const parser = new XMLParser({ ignoreAttributes: false, removeNSPrefix: true });
  const pres = parser.parse(await zip.file("ppt/presentation.xml")?.async("text") ?? ""); const size = pres?.presentation?.sldSz; const width = Number(readAttr(size, ["cx"], "12192000")); const height = Number(readAttr(size, ["cy"], "6858000"));
  const rels = parser.parse(await zip.file("ppt/_rels/presentation.xml.rels")?.async("text") ?? ""); const slideTargets = new Map<string, string>(); arr(rels?.Relationships?.Relationship).forEach((rel: any) => { if (String(readAttr(rel, ["Type"])).includes("/slide")) slideTargets.set(readAttr(rel, ["Id"]), readAttr(rel, ["Target"])); });
  const fallback = Object.keys(zip.files).filter((path) => /^ppt\/slides\/slide\d+\.xml$/.test(path)).sort((a, b) => Number(a.match(/\d+/)?.[0]) - Number(b.match(/\d+/)?.[0]));
  const ids = arr(pres?.presentation?.sldIdLst?.sldId); const candidates = ids.map((item: any) => { const target = slideTargets.get(readAttr(item, ["r:id", "id"])); return target ? (target.startsWith("ppt/") ? target : `ppt/${target.replace(/^\.\//, "")}`) : ""; }); const slidePaths = candidates.length && candidates.every((path) => Boolean(path && zip.file(path))) && new Set(candidates).size === candidates.length ? candidates : fallback;
  const media = new Map<string, string>(); for (const path of Object.keys(zip.files).filter((name) => name.startsWith("ppt/media/"))) media.set(path, dataUrl(path, await zip.files[path].async("uint8array")));
  const slides = await Promise.all(slidePaths.map(async (path) => {
    const xml = parser.parse(await zip.file(path)?.async("text") ?? ""); const root = xml?.sld?.cSld?.spTree; const slide: PptxSlide = { elements: [], width, height, text: [] }; const relPath = path.replace(/\/slides\/slide(\d+)\.xml$/, "/slides/_rels/slide$1.xml.rels"); const slideRels = parser.parse(await zip.file(relPath)?.async("text") ?? ""); const imageRels = new Map<string, string>();
    arr(slideRels?.Relationships?.Relationship).forEach((rel: any) => { if (String(readAttr(rel, ["Type"])).includes("/image")) { const id = readAttr(rel, ["Id"]); const target = readAttr(rel, ["Target"]); imageRels.set(id, zipPath(path, target)); } });
    const items = [...arr(root?.sp), ...arr(root?.pic), ...arr(root?.cxnSp)]; items.forEach((item: any) => { const xfrm = item?.spPr?.xfrm ?? item?.xfrm; const off = xfrm?.off ?? {}; const ext = xfrm?.ext ?? {}; const x = Number(readAttr(off, ["x"])) / width * 100; const y = Number(readAttr(off, ["y"])) / height * 100; const w = Number(readAttr(ext, ["cx"])) / width * 100; const h = Number(readAttr(ext, ["cy"])) / height * 100; const rotate = Number(readAttr(xfrm, ["rot"], "0")) / 60000; const texts = textNodes(item?.txBody).filter(Boolean); const embed = readAttr(item?.blipFill?.blip, ["r:embed", "embed"]); const imagePath = imageRels.get(embed); const isImage = Boolean(imagePath && media.has(imagePath)); const element: PptxElement = { kind: isImage ? "image" : texts.length ? "text" : "shape", x, y, w, h, rotate, text: texts.join(" "), fill: color(item?.spPr?.solidFill, texts.length ? "transparent" : "#ffffff22"), stroke: color(item?.spPr?.ln?.solidFill, "#ffffff44"), radius: readAttr(item?.spPr?.prstGeom, ["prst"]) === "roundRect" ? 12 : 2, src: imagePath ? media.get(imagePath) : undefined }; if (element.text) slide.text.push(element.text); if (element.w > 0 && element.h > 0) slide.elements.push(element); }); return slide;
  }));
  return { slides, name: file.name.replace(/\.pptx$/i, ""), source: file.name };
}
