import { useEffect, useMemo, useRef, useState } from "react";
import type { ChangeEvent, CSSProperties } from "react";
import { ChevronLeft, ChevronRight, FileText, FolderOpen, Grid3X3, Moon, Play, Search, Sparkles, Sun, Upload, X, Zap } from "lucide-react";
import * as pdfjsLib from "pdfjs-dist";
import { readPptx, type PptxElement } from "./lib/pptx";

type Slide = { id: string; eyebrow: string; title: string; body: string[]; accent: string; tag?: string; elements?: PptxElement[] };
type Deck = { name: string; type: string; slides: Slide[]; source?: string };
const demoSlides: Slide[] = [
  { id: "01", eyebrow: "IMMERSIVE DECK / 01", title: "Present ideas\nlike places.", body: ["A 3D canvas for stories that deserve more than a flat rectangle.", "Explore, focus, and move through every slide with cinematic depth."], accent: "violet", tag: "OPENING" },
  { id: "02", eyebrow: "THE OPPORTUNITY / 02", title: "Make the\nroom remember.", body: ["Turn static content into a spatial narrative with rhythm, focus and presence.", "Every transition is a deliberate change of perspective."], accent: "cyan", tag: "INSIGHT" },
  { id: "03", eyebrow: "THE SYSTEM / 03", title: "Structure is\na superpower.", body: ["Import a full PPTX or PDF. Keep every slide, every paragraph, every detail.", "Then present it in a stage built for attention."], accent: "amber", tag: "METHOD" },
  { id: "04", eyebrow: "THE PAYOFF / 04", title: "Leave a\nvisible trace.", body: ["A memorable presentation is not a document. It is a moment in the room.", "Build moments people can navigate, feel and repeat."], accent: "rose", tag: "OUTCOME" },
];
const clean = (text: string) => text.replace(/\s+/g, " ").trim();
async function parsePptx(file: File): Promise<Deck> { const parsed = await readPptx(file); const slides = parsed.slides.map((slide, index) => ({ id: String(index + 1).padStart(2, "0"), eyebrow: `IMPORTED PPTX / ${String(index + 1).padStart(2, "0")}`, title: slide.text[0] || `Slide ${index + 1}`, body: slide.text.slice(1, 8).length ? slide.text.slice(1, 8) : ["Diese Folie enthält grafische Elemente ohne extrahierbaren Fließtext."], accent: ["violet", "cyan", "amber", "rose"][index % 4], elements: slide.elements })); return { name: parsed.name, type: "PPTX · LAYERS", slides: slides.length ? slides : demoSlides, source: parsed.source }; }
async function parsePdf(file: File): Promise<Deck> { const pdf = await pdfjsLib.getDocument({ data: await file.arrayBuffer() }).promise; const slides: Slide[] = []; for (let pageNo = 1; pageNo <= pdf.numPages; pageNo += 1) { const page = await pdf.getPage(pageNo); const content = await page.getTextContent(); const strings = content.items.map((item) => "str" in item ? clean(item.str) : "").filter(Boolean); slides.push({ id: String(pageNo).padStart(2, "0"), eyebrow: `IMPORTED PDF / ${String(pageNo).padStart(2, "0")}`, title: strings[0] || `Page ${pageNo}`, body: strings.slice(1, 10).length ? strings.slice(1, 10) : ["Keine extrahierbaren Textobjekte auf dieser Seite."], accent: ["violet", "cyan", "amber", "rose"][pageNo % 4] }); } return { name: file.name.replace(/\.pdf$/i, ""), type: "PDF", slides: slides.length ? slides : demoSlides, source: file.name }; }

function RenderedLayers({ elements = [] }: { elements?: PptxElement[] }) { return <div className="imported-layers" aria-label="Imported slide elements">{elements.map((element, index) => { const style: CSSProperties = { left: `${element.x}%`, top: `${element.y}%`, width: `${element.w}%`, height: `${element.h}%`, transform: `rotate(${element.rotate ?? 0}deg)`, background: element.kind === "image" ? undefined : element.fill, borderColor: element.stroke, borderRadius: element.radius }; return <div className={`imported-element imported-${element.kind}`} style={style} key={`${element.kind}-${index}`}>{element.src && <img src={element.src} alt="" />}{element.kind === "text" && <span>{element.text}</span>}</div>; })}</div>; }

export default function App() {
  const [deck, setDeck] = useState<Deck>({ name: "Field Notes — 2026", type: "DEMO DECK", slides: demoSlides }); const [active, setActive] = useState(0); const [showAll, setShowAll] = useState(false); const [dark, setDark] = useState(true); const [fullscreen, setFullscreen] = useState(false); const [query, setQuery] = useState(""); const [status, setStatus] = useState("Ready to present"); const inputRef = useRef<HTMLInputElement>(null); const current = deck.slides[active] ?? deck.slides[0];
  const filtered = useMemo(() => deck.slides.filter((slide) => `${slide.title} ${slide.body.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [deck.slides, query]); const move = (delta: number) => setActive((value) => Math.min(Math.max(value + delta, 0), deck.slides.length - 1));
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "ArrowRight" || event.key === " ") move(1); if (event.key === "ArrowLeft") move(-1); if (event.key === "Escape") setFullscreen(false); if (event.key.toLowerCase() === "f") setFullscreen(true); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); });
  const loadFile = async (file: File) => { try { setStatus(`Reading layers from ${file.name}…`); const next = file.name.toLowerCase().endsWith(".pptx") ? await parsePptx(file) : await parsePdf(file); setDeck(next); setActive(0); setStatus(`${next.slides.length} slides · layers mapped`); } catch { setStatus("Could not read this file"); } }; const onFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) loadFile(file); };
  return <div className={`app-shell ${dark ? "theme-dark" : "theme-light"}`}><div className="ambient ambient-one" /><div className="ambient ambient-two" /><div className="grain" />
    <header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={17} /></div><span>IMMERSIVE</span><b>DECK</b></div><div className="top-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Theme">{dark ? <Sun size={16} /> : <Moon size={16} />}</button><button className="ghost-button" onClick={() => setShowAll(!showAll)}><Grid3X3 size={15} /> {showAll ? "Stage" : "Overview"}</button><button className="primary-button" onClick={() => setFullscreen(true)}><Play size={14} fill="currentColor" /> Present</button></div></header>
    <main className="workspace"><aside className="sidebar"><div className="sidebar-head"><div><div className="micro-label">WORKSPACE</div><h2>{deck.name}</h2></div><button className="icon-button small" onClick={() => inputRef.current?.click()}><FolderOpen size={15} /></button></div><div className="file-pill"><div className="file-icon"><FileText size={15} /></div><div><strong>{deck.type}</strong><span>{deck.source ?? "Curated example"}</span></div><span className="online-dot" /></div><div className="search-box"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search deck" /><kbd>⌘ K</kbd></div><div className="thumb-list">{filtered.map((slide) => <button key={slide.id} className={`thumb ${slide.id === current.id ? "active" : ""}`} onClick={() => setActive(deck.slides.findIndex((item) => item.id === slide.id))}><span className="thumb-number">{slide.id}</span><span className={`thumb-art ${slide.accent}`}><i /><em>{slide.tag ?? "SLIDE"}</em><strong>{slide.title.split("\n")[0]}</strong></span></button>)}</div><button className="import-button" onClick={() => inputRef.current?.click()}><Upload size={15} /> Import PPTX or PDF <span>+</span></button><input ref={inputRef} type="file" accept=".pptx,.pdf" hidden onChange={onFile} /></aside>
      <section className="stage-wrap"><div className="stage-header"><div className="stage-title"><span className="live-dot" /> <span>{status}</span></div><div className="stage-meta"><span>{String(active + 1).padStart(2, "0")} / {String(deck.slides.length).padStart(2, "0")}</span><span className="divider" /><span>16 : 9 · 3D STAGE</span></div></div>{showAll ? <div className="overview-grid">{deck.slides.map((slide, index) => <button className={`overview-card ${index === active ? "selected" : ""}`} key={slide.id} onClick={() => { setActive(index); setShowAll(false); }}><span>{slide.id}</span><div className={`mini-slide ${slide.accent}`}><small>{slide.eyebrow}</small><b>{slide.title}</b></div><p>{slide.body[0]}</p></button>)}</div> : <div className="stage"><div className="stage-grid" /><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="slide-shadow" /><div className="depth-card depth-card-back" /><article className={`hero-slide ${current.accent} ${current.elements?.length ? "has-import" : ""}`}><RenderedLayers elements={current.elements} /><div className="slide-top"><span>{current.eyebrow}</span><span className="slide-tag">{current.tag ?? "IMPORTED"}</span></div><div className="slide-content"><div className="title-column"><h1>{current.title.split("\n").map((line) => <span key={line}>{line}<br /></span>)}</h1><div className="body-copy">{current.body.map((line) => <p key={line}>{line}</p>)}</div></div><div className="visual-core"><div className="core-ring ring-one" /><div className="core-ring ring-two" /><div className="core-glow" /><span>{String(active + 1).padStart(2, "0")}</span></div></div><div className="slide-footer"><span>{current.elements?.length ? `${current.elements.length} LAYERS MAPPED` : "IMMERSIVE DECK"}</span><span>SCROLL TO EXPLORE <ChevronRight size={13} /></span></div></article><div className="stage-controls"><button onClick={() => move(-1)} disabled={active === 0}><ChevronLeft size={17} /></button><button onClick={() => move(1)} disabled={active === deck.slides.length - 1}><ChevronRight size={17} /></button></div><div className="stage-caption"><span>Navigate the deck</span><div className="progress"><i style={{ width: `${((active + 1) / deck.slides.length) * 100}%` }} /></div></div></div>}<div className="tip-bar"><span><Zap size={14} /> <b>Space</b> to move forward</span><span><b>F</b> fullscreen</span><span><b>{deck.slides.length}</b> slides, fully indexed</span></div></section></main>
    {fullscreen && <div className="fullscreen"><button className="close-fullscreen" onClick={() => setFullscreen(false)}><X size={18} /></button><div className={`fullscreen-slide ${current.accent}`}><RenderedLayers elements={current.elements} /><span className="micro-label">{current.eyebrow}</span><h1>{current.title.split("\n").map((line) => <span key={line}>{line}<br /></span>)}</h1><div className="body-copy">{current.body.map((line) => <p key={line}>{line}</p>)}</div><div className="fullscreen-index">{String(active + 1).padStart(2, "0")} <span>/ {String(deck.slides.length).padStart(2, "0")}</span></div></div><div className="fullscreen-nav"><button onClick={() => move(-1)}><ChevronLeft /></button><button onClick={() => move(1)}><ChevronRight /></button></div></div>}
  </div>;
}
